# Codemagic CI/CD configuration for building the Expo (React Native) app
# in `tn-happykids-playschool/`.
#
# This workflow builds both Android AAB (Play Store) and APK artifacts
# using Expo Prebuild + Gradle. Secrets must be configured in Codemagic:
# - CM_KEYSTORE           (base64 of your release keystore .jks)
# - CM_KEY_ALIAS          (Android key alias)
# - CM_KEYSTORE_PASSWORD  (keystore password)
# - CM_KEY_PASSWORD       (key password)
#
# Optional (for Play publishing) add: GCLOUD_SERVICE_ACCOUNT_CREDENTIALS

workflows:
  android_release:
    name: Android Release (Expo)
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      node: 20
      java: 17
      android_signing:
        # Android signing is provided via environment variables set in scripts.
        # Keep this section to ensure Android tooling is provisioned.
        properties: {}
      vars:
        APP_DIR: tn-happykids-playschool
    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - $APP_DIR/node_modules
        - $APP_DIR/android/.gradle
    scripts:
      - name: Show versions
        script: |
          echo "Node $(node -v)"
          echo "NPM  $(npm -v)"
          java -version || true
      - name: Install dependencies
        script: |
          cd "$APP_DIR"
          npm ci
      - name: Prebuild native Android project (Expo)
        script: |
          cd "$APP_DIR"
          npx expo prebuild -p android --non-interactive
      - name: Configure Android keystore
        script: |
          cd "$APP_DIR/android"
          if [ -n "$CM_KEYSTORE" ]; then
            echo "Writing release keystore"
            echo "$CM_KEYSTORE" | base64 --decode > release-keystore.jks
            # Append signing credentials to gradle.properties for release build (avoid YAML heredoc parsing issues)
            echo "MYAPP_UPLOAD_STORE_FILE=release-keystore.jks" >> gradle.properties
            echo "MYAPP_UPLOAD_KEY_ALIAS=$CM_KEY_ALIAS" >> gradle.properties
            echo "MYAPP_UPLOAD_STORE_PASSWORD=$CM_KEYSTORE_PASSWORD" >> gradle.properties
            echo "MYAPP_UPLOAD_KEY_PASSWORD=$CM_KEY_PASSWORD" >> gradle.properties
          else
            echo "WARNING: CM_KEYSTORE not set. Build will be unsigned."
          fi
      - name: Build Android App Bundle (AAB)
        script: |
          cd "$APP_DIR/android"
          ./gradlew clean bundleRelease --no-daemon
      - name: Build Android APK (optional)
        script: |
          cd "$APP_DIR/android"
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - "$APP_DIR/android/app/build/outputs/**/*.aab"
      - "$APP_DIR/android/app/build/outputs/**/*.apk"
    publishing:
      email:
        recipients:
          - dev-team@tnhappykids.in
        notify:
          success: true
          failure: true


